[package]
name = "erl_pp"
version = "0.2.0"
edition = "2024"
description = "Erlang source code preprocessor"
homepage = "https://github.com/sile/erl_pp"
repository = "https://github.com/sile/erl_pp"
readme = "README.md"
categories = ["parser-implementations"]
license = "MIT"

[dependencies]
erl_tokenize = "0.10"

[dev-dependencies]
noargs = "0.4"
